- hosts: web1
  vars: 
    USA: { Capital: 'Washington D.C.', Continent: 'NA', President: 'Donald Trump' }
  tasks:
  - name: Ansible dictionary example
    debug:
      msg: "Key is {{ item.key }} and value is  {{ item.value }}" 
    loop: "{{ USA|dict2items }}"
 
 