# Example playbook sending mail to root
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - shell: echo "hello"
      register: result

    - mail:
        subject: 'System {{ ansible_hostname }} has been successfully provisioned.'
      delegate_to: localhost