# Example playbook sending mail to root
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - mail:
        host: relay.megastar.com
        port: 25
        to: Siem <shernandez@take3tech.com>
        subject: Ansible-report
        body: 'this is a test'