---
- name: Ansible Variable Example Playbook
  hosts: web1
  tasks:
    - name: show disk space                                                                                                                         
      debug: msg="{{ ((mount.size_total - mount.size_available) / 1000000000) |  round(1,'common') }}GB of {{ (mount.size_total / 1000000000)|round(
           1, 'common') }}GB ({{ (100 * ( (mount.size_total - mount.size_available) / mount.size_available)) | round(1, 'common')}}%)"     
      loop: "{{ansible_mounts}}"
    # Parsing through Variable Dictionary
    - debug:
        msg: "Mount Point {{item.mount}} is at {{item.block_used/item.block_total*100}} percent "
      loop: "{{ansible_mounts}}"