---
- name: my first play
  hosts: web1
  tasks: 
    - name: ping
      ping:
    - name: show hostname
      command: hostname
    - name: install Apache web server
      yum:
        name: httpd
        state: present
        update_cache: true


         