- name: web servers
  hosts: web1
  become: true
  tasks:                                                
                                                                                                                        
  - debug:                                                                                                                
      msg: "disk usage {{ disk_usage_s }} of total {{ disk_total_s }} ({{ disk_usage_ratio_s }}) (should be within limit {{ disk_limit_ratio_s }})"
                                                                                                                      