- name: add a line
  hosts: web
  become: true
  tasks:
    - name: adding line to 
      lineinfile:
        path: /tmp/testfile
        line: '{{ item }}'
      with_items:
      - 'RECV_BUF_SIZE=1381600'
      - 'SEND_BUF_SIZE=1048576'
      - 'DEFAULT_SDU_SIZE=65535' 
        state: present
        backup: yes
        


