# Add a line to a file if it does not exist, without passing regexp
- name: add a line
  hosts: web
  become: true
  tasks:
    - name: adding line to 
      lineinfile:
        path: /tmp/testfile
        line: 'testing 1 2 8'
        state: present
        backup: yes