- name: add a line
  hosts: db_vm
  become: true
  tasks:
    - name: adding line to db_vm
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg.d/processes.cfg
        line: '%HOSTNAME%|__Linux__Service__CRITICAL__oswatcher = /plugins/cmas_check_process.sh/oswatcher'
        backup: yes