# Add a line to a file if it does not exist, without passing regexp
- name: update testfile
  hosts: all
  become: true
  tasks:
    - name: adding line to testfile
      lineinfile:
        path: /tmp/testfile
        line: 'testing 1 2 3'