- name: web servers
  hosts: web
  become: true
  tasks: 
    - name: install apache
      yum:
        name: httpd
        state: present
        update_cache: true
    - name: start apache server
      service:
        name: httpd
        state: started
        enabled: yes