- name: web servers
  hosts: web
  become: true
  tasks: 
    - name: install apache
      yum:
        name: httpd,php
        state: present
        update_cache: true
    - name: start apache server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: copy using inline content
      copy: 
        src: "{{ item }}"
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644
      loop:
        - index.php
    - name: remove index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: restart apache
      service:
        name: httpd
        state: restarted


  