- name: web servers
  hosts: web
  become: true
  tasks: 
    - name: install apache
      yum:
        name: httpd, php
        state: present
        update_cache: true
    - name: start apache server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: copy using inline content
      copy:
        src: "{{ item }}"
        dest: "{{document_root_path }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - index.php
    - name: copy vhost config
      copy:
        src: ansible_site.conf
        dest: "{{ vhost_config_file }}"
        owner: root
        group: root
        mode: 0644
    - name: onfigure httpd.conf
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: "^IncludeOptional"
        line: "IncludeOptional conf.d/*.conf"
    - name: restart apache
      service:
        name: httpd
        state: restarted
